# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# 버전 무관 공통 값 (모든 Stonecutter 노드에 공유됨). 버전별 값은 stonecutter.properties.toml 참고.
loader_version=0.18.4
loom_version=1.16-SNAPSHOT
